### ISSUE TITLE
return type of writerWithDefaultPrettyPrinter in ObjectMapper with ScalaObjectMapper is strange in 2.5.1

### ISSUE THREAD

**Issue by jlagerblad** [FasterXML/jackson-module-scala#201]
When switching to Jackson 2.5.1 from 2.4.4 the following code suddenly didn't compile. 
Scala version 2.10.5 (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_72)

    def toJSON(obj: AnyRef) : String = {
      val mapper = new ObjectMapper() with ScalaObjectMapper
      //  Works in 2.4.4:
      // mapper.writerWithDefaultPrettyPrinter().writeValueAsString(obj)
      // generates:
      // Error:(94, 45) value writeValueAsString is not a member of Nothing
      //  mapper.writerWithDefaultPrettyPrinter().writeValueAsString(obj)
      // Needed workaround in 2.5.1
      val writer: ObjectWriter = mapper.writerWithDefaultPrettyPrinter()
      writer.writeValueAsString(obj)
    }

**Comment by nbauernfeind** [comment]
It looks like the signature of writerWithDefaultPrettyPrinter() recent changed:

```java
     /**
      * Factory method for constructing {@link ObjectWriter} that will
      * serialize objects using the default pretty printer for indentation
      */
-    public ObjectWriter writerWithDefaultPrettyPrinter() {
-        return _newWriter(getSerializationConfig(),
+    @SuppressWarnings("unchecked")
+    public <W extends ObjectWriter> W writerWithDefaultPrettyPrinter() {
+        return (W) _newWriter(getSerializationConfig(),
                 /*root type*/ null, _defaultPrettyPrinter());
     }
```

I'm not sure why it's not being interpreted at least as an ObjectWriter. For some reason it's picking Nothing over ObjectWriter.

**Comment by nbauernfeind** [comment]
Stack overflow has a decent answer:
http://stackoverflow.com/questions/18008533/scala-how-to-go-resolve-value-is-not-a-member-of-nothing-error

So the proper usage in Scala after the change is this:

```scala
mapper.writerWithDefaultPrettyPrinter[ObjectWriter]().writeValueAsString(obj)
```

It seems pretty non-obvious, eh!?

**Comment by jlagerblad** [comment]
Thanks, that explains it! Generics seems only partially compatible in between Java and Scala...

**Comment by cowtowncoder** [comment]
Argh. This is my fault then. I did not realize this could have such a result for Scala.

The reason for change is simply to allow for different `ObjectWriter` (and similarly `ObjectReader`) sub-classes: mostly to support data formats like CSV, where there are additional configurable options.
If so, bit more state needs to be carried, and/or additional configuration/access methods.

Given this, I'll have to think whether this typing is necessary and makes sense. This, in turn, depends on whether sub-class API availability (retaining of type like `CsvWriter`) is more important than inconvenience for Scala use case.

I guess there's no chance newer Scala versions would change this, to allow type inference to work as expected.

**Comment by nbauernfeind** [comment]
This exact same problem occurs in Scala in general. For example:
```scala
scala> def example[T <: String]: T = "test".asInstanceOf[T]
example: [T <: String]=> T

scala> val e1 = example
java.lang.ClassCastException: java.lang.String cannot be cast to scala.runtime.Nothing$
  ... 33 elided

scala> val e2 = example[String]
e2: String = test
```

I don't really understand *why* it chooses to infer Nothing, because in worst case it's a String -- that seems to be the better option when nothing is specified.

I think this is a very rare thing to do (even in Java). It seems like this was done to support overwriting ObjectWriter and ObjectReader.

@cowtowncoder Why was this preferred over adding generic types to ObjectMapper?
```java
public class ObjectMapper<Writer extends ObjectWriter, Reader extends ObjectReader> ...
```

**Comment by cowtowncoder** [comment]
Simply because adding types to `ObjectMapper` would be very messy for the users, having to add largely useless type parameters for the common case of "vanilla" instance, and/or users getting tons of warnings for raw types.
Additionally I was worried about backwards compatibility, although it is likely such change would be binary compatible due type erasure.

Use of local pseudo-types is not an optimal practice, of course, but this seemed like the path of least evil.

But I am open to undoing this change in 2.6, if there is no actual usage for the feature. It was in preparation for allowing new functionality, but I don't think I had yet added anything to make use of it.

**Comment by nbauernfeind** [comment]
Another option for 2.6: you could introduce a layer with the generics. You could rename/move ObjectMapper's implementation to AbstractObjectMapper with the generics (doesn't necessarily need it to be an abstract class), and then ObjectMapper which extends AbstractObjectMapper with the default ObjectWriter/ObjectReader types. 

This makes past use cases identical and gives you a type-safe solution to the sub-classing feature.

**Comment by cowtowncoder** [comment]
I like the idea, if this could be made to work.

But wouldn't there be the problem with sub-classes like `CsvMapper`, which (due to legacy usage) still need to extend not just `AbstractObjectMapper`, but also `ObjectMapper`?
And this being the case, in Java, being unable to use different bound parameterization (since `ObjectMapper` has already bound them to `ObjectReader` / `ObjectWriter`).

So what we'd want is something like:

    public class CsvMapper
        extends ObjectMapper
        implements Mapper<CsvReader,CsvWriter> {
   }

(since there's no multiple inheritance)

but that would give a compilation error, if `ObjectMapper` implements `Mapper<ObjectReader,ObjectWriter>`.

**Comment by nbauernfeind** [comment]
Please shed some more light on this particular issue if I'm clearly missing something.

I'm suggesting having ObjectMapper be a super thin class that abstracts away the implementation detail of the generic types; effectively a token class.

```java
public class ObjectMapper 
    extends AbstractObjectMapper<ObjectReader, ObjectWriter> {
    // This class is an empty token class of AbstractObjectMapper for the general use case.
}
```

And having AbstractObjectMapper be the new name for the current implementation plus the generic signature.

```java
public class AbstractObjectMapper<Reader extends ObjectReader, Writer extends ObjectWriter>
    extends ObjectCodec
    implements Versioned,
        java.io.Serializable // as of 2.1 {
...
}
```

Which should make `CsvMapper` happier:
```java
public class CsvMapper
    extends AbstractObjectMapper<CsvReader, CsvWriter> {
...
}
```

Is there any benefit from representing this relationship through a Mapper interface instead of directly on the AbstractObjectMapper? And if there is, then we could still expose the generic types on AbstractObjectMapper.

```java
public class AbstractObjectMapper<Reader extends ObjectReader, Writer extends ObjectWriter>
    extends ObjectCodec
    implements Versioned,
        Mapper<Reader, Writer>,
        java.io.Serializable // as of 2.1 {
...
}
```

**Comment by cowtowncoder** [comment]
The big problem is that `CsvMapper` absolute MUST be a `ObjectMapper`. Otherwise much/most of existing code would stop working due to source- and binary-incompatibility.
Another perhaps even more important case is `XmlMapper`, which is used for all XML processing (whereas one might be able to use plain `ObjectMapper` with `CsvFactory`).

If we were talking about new additions it might work. But legacy compatibility is problematic.
If there was 3.x version, this could be resolved.

**Comment by christophercurrie** [comment]
Can we move the details of this discussion to the dev list? I seems to have moved beyond this scope of the original issue.

**Comment by christophercurrie** [comment]
Closing as it's both an upstream issue and an issue with Scala type inference.
