### ISSUE TITLE
Support scala 2.13.0-M4

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-module-scala#379]
There are some significant changes in the scala.collection packages.
https://github.com/scala/scala/releases/tag/v2.13.0-M4

These changes break the jackson-module-scala build. For instance, scala.collection.generic.GenericCompanion appears to have been removed.

```
[error] /Users/pj.fanning/code/jackson-module-scala/src/main/scala/com/fasterxml/jackson/module/scala/deser/SeqDeserializerModule.scala:13: object GenericCompanion is not a member of package scala.collection.generic
[error] import collection.generic.GenericCompanion
[error]        ^
[error] /Users/pj.fanning/code/jackson-module-scala/src/main/scala/com/fasterxml/jackson/module/scala/util/CompanionSorter.scala:5: object GenericCompanion is not a member of package scala.collection.generic
[error] import collection.generic.GenericCompanion
[error]        ^
[error] /Users/pj.fanning/code/jackson-module-scala/src/main/scala/com/fasterxml/jackson/module/scala/util/CompanionSorter.scala:19: not found: type GenericCompanion
[error]   def add[T[X] <: CC[X] : HKClassManifest](companion: GenericCompanion[T]): CompanionSorter[CC] = {
[error]                                                       ^
[error] /Users/pj.fanning/code/jackson-module-scala/src/main/scala/com/fasterxml/jackson/module/scala/deser/SeqDeserializerModule.scala:31: no type parameters for method add: (implicit evidence$1: scala.reflect.ClassTag[T[_]])com.fasterxml.jackson.module.scala.util.CompanionSorter[Iterable] exist so that it can be applied to arguments (scala.reflect.ClassTag[T[_]])
[error]  --- because ---
[error] argument expression's type is not compatible with formal parameter type;
[error]  found   : scala.reflect.ClassTag[?T[_$1] forSome { type _$1 }]
[error]  required: scala.reflect.ClassTag[?T[_$1] forSome { type _$1 }]
[error]     .add(IndexedSeq)
[error]         ^
[error] /Users/pj.fanning/code/jackson-module-scala/src/main/scala/com/fasterxml/jackson/module/scala/deser/SeqDeserializerModule.scala:35: object LinearSeq is not a member of package scala.collection.mutable
[error] Note: type LinearSeq exists, but it has no companion object.
[error]     .add(mutable.LinearSeq)
[error]                  ^
[error] /Users/pj.fanning/code/jackson-module-scala/src/main/scala/com/fasterxml/jackson/module/scala/deser/SeqDeserializerModule.scala:38: object MutableList is not a member of package scala.collection.mutable
[error]     .add(mutable.MutableList)
[error]                  ^
[error] /Users/pj.fanning/code/jackson-module-scala/src/main/scala/com/fasterxml/jackson/module/scala/deser/SeqDeserializerModule.scala:40: object ResizableArray is not a member of package scala.collection.mutable
[error]     .add(mutable.ResizableArray)
[error]                  ^
[error] /Users/pj.fanning/code/jackson-module-scala/src/main/scala/com/fasterxml/jackson/module/scala/deser/SeqDeserializerModule.scala:46: not found: type GenericCompanion
[error]   def companionFor(cls: Class[_]): GenericCompanion[collection.Iterable] =
[error]                                    ^
[error] /Users/pj.fanning/code/jackson-module-scala/src/main/scala/com/fasterxml/jackson/module/scala/deser/SortedSetDeserializerModule.scala:14: object SortedSetFactory is not a member of package scala.collection.generic
[error] import scala.collection.generic.SortedSetFactory
[error]        ^
[error] /Users/pj.fanning/code/jackson-module-scala/src/main/scala/com/fasterxml/jackson/module/scala/deser/SortedSetDeserializerModule.scala:39: not found: type SortedSetFactory
[error]     val module = moduleClass.getField("MODULE$").get(null).asInstanceOf[SortedSetFactory[SortedSet]]
[error]                                                                         ^
[error] /Users/pj.fanning/code/jackson-module-scala/src/main/scala/com/fasterxml/jackson/module/scala/deser/UnsortedSetDeserializerModule.scala:3: object GenericCompanion is not a member of package scala.collection.generic
[error] import scala.collection.generic.GenericCompanion
[error]        ^
[error] /Users/pj.fanning/code/jackson-module-scala/src/main/scala/com/fasterxml/jackson/module/scala/deser/UnsortedSetDeserializerModule.scala:26: no type parameters for method add: (implicit evidence$1: scala.reflect.ClassTag[T[_]])com.fasterxml.jackson.module.scala.util.CompanionSorter[scala.collection.Set] exist so that it can be applied to arguments (scala.reflect.ClassTag[T[_]])
[error]  --- because ---
[error] argument expression's type is not compatible with formal parameter type;
[error]  found   : scala.reflect.ClassTag[?T[_$1] forSome { type _$1 }]
[error]  required: scala.reflect.ClassTag[?T[_$1] forSome { type _$1 }]
[error]     .add(immutable.HashSet)
[error]         ^
[error] /Users/pj.fanning/code/jackson-module-scala/src/main/scala/com/fasterxml/jackson/module/scala/deser/UnsortedSetDeserializerModule.scala:34: not found: type GenericCompanion
[error]   def companionFor(cls: Class[_]): GenericCompanion[collection.Set] =
[error]                                    ^
[error] /Users/pj.fanning/code/jackson-module-scala/src/main/scala/com/fasterxml/jackson/module/scala/introspect/ScalaAnnotationIntrospectorModule.scala:85: object PartialFunction does not take type parameters.
[error]     val jsonCreators = PartialFunction[Annotation, JsonCreator]({ case jc: JsonCreator => jc })
[error]                                       ^
[error] /Users/pj.fanning/code/jackson-module-scala/src/main/scala/com/fasterxml/jackson/module/scala/ser/IteratorSerializerModule.scala:25: value hasDefiniteSize is not a member of Iterator[Any]
[error]     p1.hasDefiniteSize && p1.size == 1
[error]        ^
[warn] /Users/pj.fanning/code/jackson-module-scala/src/main/scala/com/fasterxml/jackson/module/scala/ser/MapSerializerModule.scala:17: Java enum WRITE_NULL_MAP_VALUES in Java enum SerializationFeature is deprecated: see corresponding Javadoc for more information.
[warn]     val m = if (config.isEnabled(SerializationFeature.WRITE_NULL_MAP_VALUES)) {
[warn]                                                       ^
[error] /Users/pj.fanning/code/jackson-module-scala/src/main/scala/com/fasterxml/jackson/module/scala/util/CompanionSorter.scala:17: not found: type GenericCompanion
[error]   private[this] val companions = new ArrayBuffer[(Class[_], GenericCompanion[CC])]()
[error]                                                             ^
[error] /Users/pj.fanning/code/jackson-module-scala/src/main/scala/com/fasterxml/jackson/module/scala/util/CompanionSorter.scala:24: not found: type GenericCompanion
[error]   def toList: List[(Class[_], GenericCompanion[CC])] = {
[error]                               ^
[error] /Users/pj.fanning/code/jackson-module-scala/src/main/scala/com/fasterxml/jackson/module/scala/util/CompanionSorter.scala:26: not found: type GenericCompanion
[error]     val output = new ListBuffer[(Class[_], GenericCompanion[CC])]()
[error]                                            ^
[error] /Users/pj.fanning/code/jackson-module-scala/src/main/scala/com/fasterxml/jackson/module/scala/util/CompanionSorter.scala:36: value isAssignableFrom is not a member of Any
[error]       if (i != j && ic.isAssignableFrom(jc)) {
[error]                        ^
[error] /Users/pj.fanning/code/jackson-module-scala/src/main/scala/com/fasterxml/jackson/module/scala/util/EnumResolver.scala:31: ambiguous reference to overloaded definition,
[error] both method map in trait StrictOptimizedIterableOps of type [B](f: e.Value => B)scala.collection.immutable.Set[B]
[error] and  method map in trait SortedSetOps of type [B](f: e.Value => B)(implicit evidence$2: Ordering[B])scala.collection.immutable.SortedSet[B]
[error] match argument types (e.Value => (String, e.Value))
[error]     val map: Map[String, e.type#Value] = valueSet.map(v => (v.toString, v)).toMap
[error]                                                   ^
[warn] 8 warnings found
[error] 20 errors found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 6 s, completed 25-Jun-2018 15:20:17
```

**Comment by pjfanning** [comment]
Probably supercedes https://github.com/FasterXML/jackson-module-scala/pull/355

**Comment by nbauernfeind** [comment]
Looks like GenericCompanion is now scala.collection.Factory. See https://github.com/scala/scala/blob/2.13.x/src/library/scala/collection/Factory.scala.

Do you know if there are or will be other differences? If there are enough differences it might make sense to maintain separate branches. I think dropping 2.10 support is sufficient to start using scala reflection - so unfortunately that's not a pro, too.

**Comment by pjfanning** [comment]
We could add overridden source for the couple of classes that won't compile in scala 2.13.0-M4.
`src/main/scala-2.13+` can be used for this source (but may require an sbt upgrade).
https://github.com/rickynils/scalacheck/pull/411/files change for src/main/scala-2.13+/org/scalacheck/ScalaVersionSpecific.scala is an example

**Comment by nbauernfeind** [comment]
Ok, that's interesting. Thanks. Some of these changes feel pervasive - since Scala 2.13 is explicitly trying to simplify the collections implementation.

I've fixed all of the compilation problems so far. Something is funky with scalatest though (that I haven't figured out yet). The matcher related test pieces are not compiling yet. You can see my progress thus far here:

https://github.com/nbauernfeind/jackson-module-scala/tree/scala-2.13

**Comment by pjfanning** [comment]
I got your branch to compile and was able to get tests to pass by removing/modifying a few tests
https://github.com/nbauernfeind/jackson-module-scala/pull/1

**Comment by nbauernfeind** [comment]
As I'd mentioned elsewhere, the issue I ran into was from using JDK10. It works on JDK8. Hopefully it's something the scalatest / scala community figures out before 2.13 has an official release.

My branch is looking very solid. A few more minor changes and I think it'll be good to push to master. I haven't thought about the most appropriate way to release a 2.13 version yet though. Do you have a desired timeline?

**Comment by pjfanning** [comment]
Would it be possible to publish a jackson-module-scala_2.13.0-M4:2.9.6 based on your changes (when you're happy with them)? I have some swagger utilities that I'd like to publish a 2.13.0-M4 compatible jar for and this work relies on jackson-module-scala.
It looks like you've managed to continue to support older scala versions and don't need any breaking changes for those older scala versions.

**Comment by nbauernfeind** [comment]
That release plan seems reasonable.

I really wish scala had some sort of way to include/exclude blocks of code based on the compiler version. It turns out scala 2.12 added `mutable.SortedMap` and `mutable.TreeMap`. I integrated them in part of my cleanup/improvements to the Map Deserializer Modules, only to discover it doesn't compile.

It'll be annoying to have pre/post 2.12 directory structures too. I'm contemplating making scala-$ver directories for each supported scala version. I feel like I've gotten the differences into a barebones pattern so the copied code is minimal. Though this seems like the cleanest pattern forward.

It's slightly frustrating nonetheless.

**Comment by nbauernfeind** [comment]
This is now merged, and I've back-released 2.9.6. As usual, it will take a few hours for the release to propagate to maven central. Please report any issues you run into.
